excel_reader:
  input_file: "C:/dev/sample_data/ncr_ride_bookings.xlsx"
  sheet_name: null         
  skip_empty_sheets: true  
  encoding: "utf-8"        


parquet_writer:
  output_dir: "C:/dev/sample_data/processed"
  compression: "snappy"     
  overwrite: true
  sanitize_names: true 

logging:
  level: "INFO"
  logger_name: "excel_pipeline"